### ISSUE TITLE
Add fields to status page

### ISSUE THREAD

**Issue by benjwadams** [ioos/glider-dac-status#24]
Add "total number of files" and "latest file modified" time fields for netCDF files.  This will help diagnose when the status issues are displaying due to no files being present in a directory for a particular glider deployment.

**Comment by kerfoot** [comment]
@benjwadams  **.nc File Count** field isn't displaying the proper number of nc files submitted by the user.  Clicking on the ng291, ng296 and ng619 link takes you to the DAC page which shows >1 file submitted by the data provider.

**Comment by benjwadams** [comment]
Implemented a while back by #25, closing.
